# project settings tabs

root:
    kind: tabs
    groups:
        projectAdmin: Project Administration
    contents:
        ${quarantine}
        ${prearchive}
        ${projectAnon}
        ${seriesImport}
        ${dicomPETMR}
        ${PETTracerSettings}
        ${notifications}
        ${scanType}
        ${projectResources}
        #${siteConfigObj}
        #${projectSettingsJS}

# define tabs

siteConfigObj:
    tag: "script|src=/scripts/xnat/data/siteConfig.js.jsp"

quarantine:
    show: "{{XNAT.data.siteConfig.uiAllowQuarantine}}"  # render depending on the value of this variable
    kind: tab
    label: Quarantine
    group: projectAdmin
    contents:
        ${quarantineSettings}

prearchive:
    show: "{{XNAT.data.siteConfig.projectAllowAutoArchive}}"  # render depending on the value of this variable
    kind: tab
    label: Prearchive
    group: projectAdmin
    contents:
        ${prearchiveSettings}

projectAnon:
    kind: tab
    label: Anonymization
    group: projectAdmin
    contents:
        ${projectAnonForm}

seriesImport:
    kind: tab
    label: Series Import Filters
    group: projectAdmin
    contents:
        ${seriesImportForm}

eventHandlers:
    kind: tab
    label: Event Handlers
    group: projectAdmin
    contents:
        ${eventHandlerSetup}

projectResources:
    kind: tab
    label: Project Resource Settings
    group: projectAdmin
    contents:
        ${projectResourceSettings}

dicomPETMR:
    kind: tab
    label: DICOM PET/MR
    group: projectAdmin
    contents:
        ${dicomConfig}

scanType:
    kind: tab
    label: Scan Type Mapping
    group: projectAdmin
    contents:
        ${scanTypeMapping}

PETTracerSettings:
    kind: tab
    label: PET Tracers
    group: projectAdmin
    contents:
        ${PETTracers}

notifications:
    kind: tab
    label: Notifications
    group: projectAdmin
    contents:
        ${notificationsConfig}



quarantineSettings:
    kind: panel.form
    id: quarantine-settings
    label: Define Quarantine Settings
    load: "#[XNAT.app.projectSettings.getQuarantineCode]"
    action: "#[XNAT.app.projectSettings.setQuarantineCode]"
    #load: /data/projects/{{XNAT.data.context.project}}/quarantine_code > [[quarantine]]
    #action: /data/projects/{{XNAT.data.context.project}}/quarantine_code/[[quarantine]]?XNAT_CSRF={{csrfToken}}
    #method: PUT
    contents:
        quarantineRadios:
            kind: input.radioGroup
            name: quarantine
            #value: $? /data/projects/{{XNAT.data.context.project}}/quarantine_code
            options:
                yes:
                    label: "Yes"
                    value: "1"
                    description: >
                        All new experiments (and modified experiments) are quarantined and must be specifically activated.
                no:
                    label: "No"
                    value: "0"
                    description: >
                        New and modified experiments will not be quarantined.

prearchiveSettings:
    kind: panel.form
    id: prearchive-settings
    label: Define Prearchive Settings
    load: "#[XNAT.app.projectSettings.getPrearhchiveCode]"
    action: "#[XNAT.app.projectSettings.setPrearchiveCode]"
    #load: /data/projects/{{XNAT.data.context.project}}/prearchive_code > [[prearchive]]
    #action: /data/projects/{{XNAT.data.context.project}}/prearchive_code/[[prearchive]]?XNAT_CSRF={{csrfToken}}
    #method: PUT
    contents:
        prearchiveRadios:
            kind: input.radioGroup
            name: prearchive
            #value: $? /data/projects/{{XNAT.data.context.project}}/prearchive_code
            options:
                prearc0:
                    id: prearchive-0
                    value: "0"
                    label: ""
                    description: >
                        All image data should be placed in a temporary location (prearchive) before being
                        manually transferred into the permanent archive.
                prearc4:
                    id: prearchive-4
                    value: "4"
                    label: ""
                    description: >
                        All image data will be placed into the archive automatically, but anything matching
                        existing files will be rejected. Data which doesn't match a pre-existing project will
                        be placed in an 'Unassigned' project.
                prearc5:
                    id: prearchive-5
                    value: "5"
                    label: ""
                    description: >
                        All image data will be placed into the archive automatically and will overwrite existing files.
                        Data which doesn't match a pre-existing project will be placed in an 'Unassigned' project.

dicomConfig:
    kind: panel.form
    id: dicom-separate-petmr
    label: DICOM Configuration
    #load: /data/projects/{{XNAT.data.context.project}}/config/separatePETMR/config?contents=true > [[separatePETMR]]
    #action: /data/projects/{{XNAT.data.context.project}}/config/separatePETMR/config?inbody=true&XNAT_CSRF={{csrfToken}} < [[separatePETMR]]
    load: "#[XNAT.app.projectSettings.getDicomConfig]"
    action: "#[XNAT.app.projectSettings.setDicomConfig]"
    contents:
        separatePETMR:
            kind: panel.select.single
            name: separatePETMR
            id: dicom-petmr-menu
            label: "Separate PET-MR?"
            description: >
                Should data generated by PET-MR scanners be created as a single PET/MR imaging session,
                created as a single PET imaging session, or separated into PET and MR sessions?
            options:
                system: "Use the system default"
                petmr: "Create as PET/MR session"
                pet: "Create as PET session"
                separate: "Separate into PET and MR sessions"


scanTypeMapping:
    kind: panel.form
    id: scan-type-mapping
    label: Define Scan Type Mapping
    action: "#[XNAT.app.projectSettings.setScanTypeMapping]"
    contents:
        scan_type_mapping:
            kind: input.radioGroup
            name: scan_type_mapping
            id: scan-type-mapping-radios
            options:
                yes:
                    label: "Yes"
                    value: "true"
                    description: >
                        Incoming scans will have their type attribute set based on historical scan type mapping data.
                no:
                    label: "No"
                    value: "false"
                    description: >
                        Incoming scans will have their type attribute set to be identical to their series description.

PETTracers:
    kind: panel.form
    id: pet-tracers
    label: PET Tracers
    action: "#[XNAT.app.projectSettings.setPetTracer]"
    contents:
        petTracersSettings:
            tag: textarea#pet-tracers-settings.hidden|name=petTracersSettings
        enableTracers:
            kind: panel.input.switchbox
            name: status
            id: enable-pet-tracers
            label: Enable Project PET Tracers
            onText: PET Tracers Enabled
            offText: PET Tracers Disabled
        contents:
            kind: panel.textarea
            name: contents
            id: pet-tracer-contents
            label: PET Tracer List
            description: >
                List entries should be separated by whitespace.
        helperJS:
            tag: script
            content: >
                $(document).on('click', '#enable-pet-tracers', function(){
                    this.value = this.checked ? 'enabled' : 'disabled'
                })

# --------------------------------------------------
# ==================================================





# ==================================================
# 'Notifications' tab elements
# --------------------------------------------------

notificationsConfig:
    kind: panel.form
    id: notifications-config
    label: Notifications Configuration
    contents:
        notif_list:
            kind: panel.textarea
            name: notif_list
            label: Email Addresses
            validation: emails allow-empty
            description: >
                Emails should be comma separated (i.e. tim@somewhere.com,jenny@somewhere.com).

# --------------------------------------------------
# ==================================================





# ==================================================
# 'Anonymization' tab elements
# --------------------------------------------------

projectAnonForm:
    kind: panel.form
    id: project-anon-form
    label: Project Anonymization Script
    load: "#[XNAT.app.projectSettings.getProjectAnonScript]"
    action: "#[XNAT.app.projectSettings.setProjectAnonScript]"
    contents:
        enableScript:
            kind: panel.switchbox
            label: Enable Script
            id: project-anon-enable
            name: enableScript
            onText: Project Anon Script Enabled
            offText: Project Anon Script Disabled
        anonScriptText:
            kind: panel.textarea
            id: project-anon-script
            label: Script
            name: anonScriptText
#            description: >
#                Double-click to open in a code editor dialog.

# --------------------------------------------------
# ==================================================





# ==================================================
# 'Series Import' tab elements
# --------------------------------------------------

seriesImportForm:
    kind: panel.form
    id: series-import-form
    label: Series Import Filters
#    load: /data/projects/{{XNAT.data.context.projectID}}/config/seriesImportFilter/config | :ResultSet:Resul:0:contents
#    action: /data/projects/{{XNAT.data.context.projectID}}/config/seriesImportFilter/config?status=[[enabled]] < [[seriesImportFilter]]
#    contentType: text/plain
#    params:
#        - inbody=true
#        - XNAT_CSRF={{csrfToken}}
    load: "#[XNAT.app.projectSettings.getSeriesImportFilter]"
    action: "#[XNAT.app.projectSettings.setSeriesImportFilter]"
    contents:
        about:
            tag: p
            content: >
                This is the series import filter applied to incoming and archiving DICOM resources for your project.
                This filter can also be supplemented by the site-wide series import filter.
        filterSettingsSubhead:
            kind: panel.subhead
            label: Filter Settings
        enableFilter:
            kind: panel.input.switchbox
            name: enabled
            id: series-import-enable
            label: Enable Filter
            options: 'true|false'
            onText: Filter Enabled
            offText: Filter Disabled
        filterMode:
            kind: panel.select.single
            label: Mode
            name: mode
            id: filter-mode
            options:
                whitelist: Whitelist
                blacklist: Blacklist
                modalityMap: Modality Map
            description: >
                Creating a whitelist means that <i>only</i> DICOM series with a series description
                that matches one of series filter patterns will be considered by XNAT import tools
                such as the <a href="/app/template/UploadAssistantPage.vm">XNAT Upload
                Assistant</a>. Creating a blacklist means that all DICOM series will be considered
                <i>except</i> for series that have one of the specified series filter patterns. A
                modality map lets you specify boolean expressions in JavaScript that can use DICOM
                header values from incoming DICOM objects to decide the appropriate modality for the
                destination session.
        seriesImportFilter:
            kind: panel.textarea
            id: series-import-filter
            name: list
            element:
                rows: 20
            description: >
                The series filters can be written as exact string matches, but also can be regular expressions. The regular expressions are evaluated
                using the <a href="http://docs.oracle.com/javase/tutorial/essential/regex/" target="_blank">Java regular expression syntax</a>. These
                expressions are case-insensitive, i.e. the string "SAG LOCALIZER" will also match "Sag Localizer".

# --------------------------------------------------
# ==================================================




projectResourceSettings:
    kind: panel
    contents:
        projectResourcSettingsTemplate:
            template: 'id=project-resource-settings-template'



# projectSettings.js file
projectSettingsJS:
    tag: "script|src=/scripts/xnat/app/projectSettings.js"





# DEMO TAB
users:
    kind: tab
    label: User List
    group: projectAdmin
    contents:
        ${userTable}

userTable:
    kind: table.dataTable
    url: /data/projects/{{XNAT.data.context.project}}/users
    columns:
        NAME:
            label: Name
            filter: true
            sort: true
            apply: >
                !? function(){
                    return this.firstname + ' ' + this.lastname
                }
        login:
            label: Username
            filter: true
            sort: true
        email:
            label: Email
            filter: true
            sort: true
            html: >
                <a href="mailto:__VALUE__">__VALUE__</a>
        displayname:
            label: Group
            filter: true
            sort: true
